//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGroceryStoreApp.Models.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Аккаунт
    {
        public int Код { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public byte УровеньДоступа { get; set; }
        public int КодСотрудника { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
    }
}
