//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGroceryStoreApp.Models.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class НаселённыйПункт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public НаселённыйПункт()
        {
            this.Адрес = new HashSet<Адрес>();
            this.Улица = new HashSet<Улица>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public int Тип { get; set; }
        public int КодРегиона { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Адрес> Адрес { get; set; }
        public virtual Регион Регион { get; set; }
        public virtual ТипНаселённогоПункта ТипНаселённогоПункта { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Улица> Улица { get; set; }
    }
}
