//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGroceryStoreApp.Models.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class СписаниеТовар
    {
        public int КодСписания { get; set; }
        public int КодТовара { get; set; }
        public decimal Количество { get; set; }
    
        public virtual Списание Списание { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
