//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGroceryStoreApp.Models.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Стеллаж
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Стеллаж()
        {
            this.ТорговыйЗалСтеллаж = new HashSet<ТорговыйЗалСтеллаж>();
        }
    
        public int Код { get; set; }
        public int Тип { get; set; }
        public bool Статус { get; set; }
        public int КодФилиала { get; set; }
    
        public virtual ТипСтелажа ТипСтелажа { get; set; }
        public virtual Филиал Филиал { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТорговыйЗалСтеллаж> ТорговыйЗалСтеллаж { get; set; }
    }
}
