//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMGroceryStoreApp.Models.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ТипСтелажа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ТипСтелажа()
        {
            this.Стеллаж = new HashSet<Стеллаж>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public byte КоличествоСекций { get; set; }
        public int ШиринаСекции { get; set; }
        public int ГлубинаСекции { get; set; }
        public int ВысотаСекции { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Стеллаж> Стеллаж { get; set; }
    }
}
